[server]
enableCORS = true
enableXsrfProtection = true
headless = true
maxUploadSize = 50
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "auto"
showErrorDetails = false

[logger]
level = "info" 